const VisualState = {
    EMPTY: 'EMPTY',
    PENDING: 'PENDING',
    SHOW: 'SHOW',
}
const SELECT_TAB = 'SELECT_TAB'
const DISPLAY_INFO_PANEL = 'DISPLAY_INFO_PANEL'
const F1_FORM_SELECT_SYMBOL = 'F1_FORM_SELECT_SYMBOL'
const F1_FORM_SELECT_TABLE = 'F1_FORM_SELECT_TABLE'
const F1_FORM_SET_DATA = 'F1_FORM_SET_DATA'
const UPDATE_VISUAL_STATE = 'UPDATE_VISUAL_STATE'

const TAB_CODES = {
    F1FORM: 'TABS_CODE_F1FORM',
}


export { 
    VisualState, SELECT_TAB, DISPLAY_INFO_PANEL, F1_FORM_SELECT_SYMBOL,
    F1_FORM_SELECT_TABLE, UPDATE_VISUAL_STATE, F1_FORM_SET_DATA, TAB_CODES 
}

